### ISSUE TITLE
Comparing files ends with nullpointer

### ISSUE THREAD

**Issue by Siltyx** [yoep/xsd-compare#5]
Comparing OpenDRIVE 1.4 H and OpenDRIVE 1.5 M results in nullpointer. 
Download here: http://www.opendrive.org/download.html

2019-06-12 11:23:43.940 ERROR 16739 --- [lication Thread] com.compare.xsd.views.MainView           : null

java.lang.NullPointerException: null
	at com.compare.xsd.comparison.model.xsd.impl.AbstractXsdNode.loadType(AbstractXsdNode.java:158) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.loadComplexType(XsdElement.java:156) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.init(XsdElement.java:140) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.<init>(XsdElement.java:65) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.processComplexGroup(XsdElement.java:174) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.loadComplexType(XsdElement.java:154) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.init(XsdElement.java:140) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.<init>(XsdElement.java:65) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.processComplexGroup(XsdElement.java:174) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.loadComplexType(XsdElement.java:154) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.init(XsdElement.java:140) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.<init>(XsdElement.java:65) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.processComplexGroup(XsdElement.java:174) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.loadComplexType(XsdElement.java:154) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.init(XsdElement.java:140) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdElement.<init>(XsdElement.java:48) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdDocument.init(XsdDocument.java:83) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.model.xsd.impl.XsdDocument.<init>(XsdDocument.java:32) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.XsdLoader.load(XsdLoader.java:74) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.comparison.XsdLoader.chooseAndLoad(XsdLoader.java:54) ~[classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.views.MainView.loadTree(MainView.java:239) [classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.views.MainView.loadTree(MainView.java:229) [classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.views.MainView.loadNextAvailableTree(MainView.java:180) [classes!/:0.0.4-SNAPSHOT]
	at com.compare.xsd.views.components.MenuComponent.loadNextAvailableTree(MenuComponent.java:44) ~[classes!/:0.0.4-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71) ~[na:1.8.0_201]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275) ~[na:1.8.0_201]
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771) ~[jfxrt.jar:na]
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) ~[jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:na]
	at javafx.scene.Node.fireEvent(Node.java:8411) ~[jfxrt.jar:na]
	at javafx.scene.control.Button.fire(Button.java:185) ~[jfxrt.jar:na]
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182) ~[jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96) ~[jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) ~[jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757) ~[jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485) ~[jfxrt.jar:na]
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762) ~[jfxrt.jar:na]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_201]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$345(GlassViewEventHandler.java:432) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431) ~[jfxrt.jar:na]
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555) ~[jfxrt.jar:na]
	at com.sun.glass.ui.View.notifyMouse(View.java:937) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$203(GtkApplication.java:139) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]

**Comment by yoep** [comment]
One of the type definitions didn't contain a namespace (which is strange) and caused one of the type checks to fail.
